export const types = {
    FETCH_WEATHER_DATA_SUCCEEDED : 'FETCH_WEATHER_DATA_SUCCEEDED',
    FETCH_WEATHER_DATA_ERROR : 'FETCH_WEATHER_DATA_ERROR',
    SET_FIVE_DAYS_WEATHER_DATA : 'SET_FIVE_DAYS_WEATHER_DATA',
    SET_ONE_DAY_HOURS_WEATHER_DATA : 'SET_ONE_DAY_HOURS_WEATHER_DATA',
    RESET_ONE_DAY_HOURS_WEATHER_DATA : 'RESET_ONE_DAY_HOURS_WEATHER_DATA',
    SET_LOCATION : 'SET_LOCATION',
    DATA_REQUEST_SENT : 'DATA_REQUEST_SENT',
    DATA_RESPONSE_RECEIVED : 'DATA_RESPONSE_RECEIVED'
};


