export const FETCH_WEATHER_DATA_SUCCEEDED = 'FETCH_WEATHER_DATA_SUCCEEDED';
export const FETCH_WEATHER_DATA_ERROR = 'FETCH_WEATHER_DATA_ERROR';
export const SET_FIVE_DAYS_WEATHER_DATA = 'SET_FIVE_DAYS_WEATHER_DATA';
export const SET_ONE_DAY_HOURS_WEATHER_DATA = 'SET_ONE_DAY_HOURS_WEATHER_DATA';
export const RESET_ONE_DAY_HOURS_WEATHER_DATA = 'RESET_ONE_DAY_HOURS_WEATHER_DATA';
export const SET_LOCATION = 'SET_LOCATION';
export const DATA_REQUEST_SENT = 'DATA_REQUEST_SENT';
export const DATA_RESPONSE_RECEIVED = 'DATA_RESPONSE_RECEIVED';


